# Netlify configuration for construction-erp-demo
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm ci && npm run build:client"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18.20.3"

# Single Page App routing: serve index.html for all paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional security headers (Netlify sets some by default; adjust as needed)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:; connect-src 'self' https: ws: wss:; img-src 'self' data: blob: https:; font-src 'self' data: https:;"

